server:
  port: 8761
spring:
  application:
    name: eureka
# https://cloud.spring.io/spring-cloud-netflix/reference/html/#disabling-ribbon-with-eureka-server-and-client-starters    
  cloud.loadbalancer.ribbon.enabled: false
# 关于时间，以下仅仅测试用途，更多参考 https://www.cnblogs.com/liukaifeng/p/10052594.html 按需配置
eureka:
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true
    use-read-only-response-cache: false
  client:
    # eureka client间隔多久去拉取服务注册信息 默认30s
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: ${EUREKA_SERVER}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    instance-id: ${EUREKA_INSTANCE_HOSTNAME}:${server.port}
    
